# -*- coding: utf-8 -*-
"""Pickling_Dataframe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KMcbEej1AP3L0z41xXN7RkEqCkRq0BWm
"""

# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Fmou4Ou0EDyp2kewb9tZ3dUCINImaiQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading data from dataset
df=pd.read_csv("Final Test File.csv")
df.shape
df.head(10)

#Selecting rows on specific condition
ddf=df[df['Vintage']>200]
ddf.shape

#Sorting the values based on Vintage column
df.sort_values(by=['Vintage'])

#Grouping the dataset based on Region_Code
g=df.groupby('Region_Code')
for Region_Code,i in g:
  print(Region_Code)
  print(i)
sg=g.get_group(3)
sg 

# Calculation Of Mean in each Group
s=df.groupby('Region_Code').mean()

#Adding a new column to existing dataset
df['Annual_Premium']=s['Policy_Sales_Channel']
df.head(10)


#Pickling of dataframe

df.to_pickle('Vehicle_Insurance.pkl')

#Reading pickle file 
newdf=pd.read_pickle('Vehicle_Insurance.pkl')
newdf.head()

#Scatter plot with labeled axis

x=df['id'].to_list()
y=df['Vintage'].to_list()
plt.scatter(x,y, color='green')
plt.xlabel('Id')
plt.ylabel("Vintage")
plt.show

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""